package io.muzoo.ssc.controlmap.web;

import io.muzoo.ssc.controlmap.repository.UserRepository;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;

/**
 * Builds the provenance lines stamped on every exported report — when it was generated and by whom
 * (display name + role, resolved from the session email; the raw email if the account is unknown).
 * One component (SRP/DRY) so every report family — the tabular registers, the posture document, and
 * the future admin audit export — carries identical audit-evidence provenance.
 */
@Component
public class ReportProvenance {

    /** Minute precision is enough for "when was this pulled"; audit *rows* keep their own seconds. */
    private static final DateTimeFormatter TS = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm 'UTC'")
            .withZone(ZoneOffset.UTC);

    private final UserRepository users;

    public ReportProvenance(UserRepository users) {
        this.users = users;
    }

    public String generatedLine(Instant now) {
        return "Generated " + TS.format(now);
    }

    public String generatedByLine(String actorEmail) {
        return "Generated by " + users.findByEmail(actorEmail)
                .map(u -> u.getName() + " (" + StringUtils.capitalize(u.getRole().name().toLowerCase(Locale.ROOT)) + ")")
                .orElse(actorEmail);
    }
}
