package io.muzoo.ssc.controlmap.web;

import io.muzoo.ssc.controlmap.report.RenderedReport;
import org.springframework.http.ContentDisposition;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * Report export API (PLAN §10), authenticated (any signed-in user). Streams a findings, coverage,
 * audit or posture report as a file download; the {@code ?format=} selects the format. Unknown format
 * → 400, unknown framework → 404 (consistent error model). Tabular reports are built by
 * {@link ReportService}; the multi-section posture report by {@link PostureReportService} — both via
 * the ReportFactory. Every export records the caller as its "generated by" provenance.
 */
@RestController
@RequestMapping("/api/reports")
public class ReportController {

    private final ReportService reportService;
    private final PostureReportService postureReportService;

    public ReportController(ReportService reportService, PostureReportService postureReportService) {
        this.reportService = reportService;
        this.postureReportService = postureReportService;
    }

    @GetMapping("/findings")
    public ResponseEntity<byte[]> findings(@RequestParam(value = "format", defaultValue = "csv") String format,
                                           Authentication authentication) {
        return download(reportService.findingsReport(format, authentication.getName()));
    }

    @GetMapping("/coverage")
    public ResponseEntity<byte[]> coverage(
            @RequestParam("framework") String framework,
            @RequestParam(value = "format", defaultValue = "csv") String format,
            Authentication authentication) {
        return download(reportService.coverageReport(framework, format, authentication.getName()));
    }

    @GetMapping("/audit")
    public ResponseEntity<byte[]> audit(@RequestParam(value = "format", defaultValue = "csv") String format,
                                        Authentication authentication) {
        return download(reportService.auditReport(format, authentication.getName()));
    }

    /** The comprehensive posture/auditor report (multi-section document rather than a register). */
    @GetMapping("/posture")
    public ResponseEntity<byte[]> posture(@RequestParam(value = "format", defaultValue = "pdf") String format,
                                          Authentication authentication) {
        return download(postureReportService.postureReport(format, authentication.getName()));
    }

    private static ResponseEntity<byte[]> download(RenderedReport report) {
        ContentDisposition disposition = ContentDisposition.attachment().filename(report.filename()).build();
        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, disposition.toString())
                .contentType(MediaType.parseMediaType(report.contentType()))
                .body(report.body());
    }
}
