-- V2 — core domain schema (PLAN §3).
-- Mirrors the JPA entities exactly (Hibernate runs ddl-auto: validate). CHECK / UNIQUE / FK
-- constraints and indexes are integrity hardening; Hibernate's validator ignores them.

-- Users. `user` is reserved in PostgreSQL, so the table is `app_user`.
CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT ck_app_user_role CHECK (role IN ('ANALYST', 'REVIEWER'))
);

-- Frameworks.
CREATE TABLE framework (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    version VARCHAR(50)  NOT NULL,
    CONSTRAINT uq_framework_name_version UNIQUE (name, version)
);

-- Controls (belong to a framework; unique code within a framework).
CREATE TABLE control (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    framework_id BIGINT       NOT NULL,
    code         VARCHAR(50)  NOT NULL,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,
    CONSTRAINT fk_control_framework FOREIGN KEY (framework_id) REFERENCES framework (id),
    CONSTRAINT uq_control_framework_code UNIQUE (framework_id, code)
);
CREATE INDEX ix_control_framework ON control (framework_id);

-- Findings (owned by a user; embedded asset_* columns; CVSS 0.0–10.0 when present).
CREATE TABLE finding (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference       VARCHAR(20)  NOT NULL,
    title           VARCHAR(255) NOT NULL,
    description     TEXT,
    severity        VARCHAR(20)  NOT NULL,
    cvss_score      NUMERIC(3, 1),
    status          VARCHAR(20)  NOT NULL,
    owner_id        BIGINT       NOT NULL,
    asset_name      VARCHAR(255) NOT NULL,
    asset_env       VARCHAR(255),
    asset_component VARCHAR(255),
    asset_url       VARCHAR(255),
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_finding_reference UNIQUE (reference),
    CONSTRAINT fk_finding_owner FOREIGN KEY (owner_id) REFERENCES app_user (id),
    CONSTRAINT ck_finding_severity CHECK (severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')),
    CONSTRAINT ck_finding_cvss CHECK (cvss_score IS NULL OR (cvss_score >= 0 AND cvss_score <= 10)),
    CONSTRAINT ck_finding_status CHECK (status IN
        ('OPEN', 'IN_PROGRESS', 'SUBMITTED', 'APPROVED', 'RETURNED', 'REMEDIATED', 'ACCEPTED'))
);
CREATE INDEX ix_finding_owner ON finding (owner_id);
CREATE INDEX ix_finding_status ON finding (status);

-- Finding ↔ control mappings (the many-to-many join, with AI provenance).
CREATE TABLE finding_control_mapping (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id    BIGINT      NOT NULL,
    control_id    BIGINT      NOT NULL,
    source        VARCHAR(20) NOT NULL,
    ai_confidence DOUBLE PRECISION,
    ai_rationale  TEXT,
    ai_model      VARCHAR(100),
    CONSTRAINT fk_fcm_finding FOREIGN KEY (finding_id) REFERENCES finding (id) ON DELETE CASCADE,
    CONSTRAINT fk_fcm_control FOREIGN KEY (control_id) REFERENCES control (id),
    CONSTRAINT uq_fcm_finding_control UNIQUE (finding_id, control_id),
    CONSTRAINT ck_fcm_source CHECK (source IN ('MANUAL', 'AI_SUGGESTED')),
    CONSTRAINT ck_fcm_ai_confidence CHECK (ai_confidence IS NULL OR (ai_confidence >= 0 AND ai_confidence <= 1))
);
CREATE INDEX ix_fcm_finding ON finding_control_mapping (finding_id);
CREATE INDEX ix_fcm_control ON finding_control_mapping (control_id);

-- Audit log (workflow trail; `timestamp` is reserved, so the column is `occurred_at`).
CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id  BIGINT      NOT NULL,
    actor_id    BIGINT      NOT NULL,
    action      VARCHAR(50) NOT NULL,
    from_status VARCHAR(20),
    to_status   VARCHAR(20),
    comment     TEXT,
    occurred_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_audit_finding FOREIGN KEY (finding_id) REFERENCES finding (id) ON DELETE CASCADE,
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_id) REFERENCES app_user (id)
);
CREATE INDEX ix_audit_finding ON audit_log (finding_id);
