-- V6 — ADMIN role, user deactivation (offboarding), and a user-management audit trail.

-- Allow ADMIN in the role check (analyst authors, reviewer reviews, admin administers).
ALTER TABLE app_user DROP CONSTRAINT ck_app_user_role;
ALTER TABLE app_user ADD CONSTRAINT ck_app_user_role CHECK (role IN ('ANALYST', 'REVIEWER', 'ADMIN'));

-- Account activation: a deactivated user cannot authenticate (and is force-logged-out on next request).
-- Existing rows default to active.
ALTER TABLE app_user ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

-- Audit trail for admin user-management actions (role change, (de)activation, password reset). Kept
-- separate from the finding-scoped audit_log; the target user is retained even after deactivation.
CREATE TABLE user_audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id       BIGINT      NOT NULL,
    target_user_id BIGINT      NOT NULL,
    action         VARCHAR(50) NOT NULL,
    detail         TEXT,
    occurred_at    TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_user_audit_actor FOREIGN KEY (actor_id) REFERENCES app_user (id),
    CONSTRAINT fk_user_audit_target FOREIGN KEY (target_user_id) REFERENCES app_user (id)
);

CREATE INDEX ix_user_audit_occurred ON user_audit_log (occurred_at DESC);
