package io.muzoo.ssc.controlmap.web;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import io.muzoo.ssc.controlmap.domain.Asset;
import io.muzoo.ssc.controlmap.domain.AuditLog;
import io.muzoo.ssc.controlmap.domain.Finding;
import io.muzoo.ssc.controlmap.domain.FindingStatus;
import io.muzoo.ssc.controlmap.domain.Role;
import io.muzoo.ssc.controlmap.domain.Severity;
import io.muzoo.ssc.controlmap.domain.User;
import io.muzoo.ssc.controlmap.repository.AuditLogRepository;
import io.muzoo.ssc.controlmap.repository.FindingRepository;
import io.muzoo.ssc.controlmap.repository.UserRepository;
import io.muzoo.ssc.controlmap.web.dto.FindingSummary;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.List;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.transaction.annotation.Transactional;

/**
 * The comprehensive posture/auditor report (#posture-report): endpoint contract (content types,
 * provenance, 400/401) and content spot-checks of both renderings — the PDF via extracted text, the
 * CSV via its blocks. Assertions are contains-based (never exact counts) so seeded dev data cannot
 * break them; the scenario findings use unique references.
 */
@SpringBootTest
@AutoConfigureMockMvc
@Transactional
class PostureReportTest {

    private static final String ANALYST = "analyst@posture-report.test";

    @Autowired private MockMvc mockMvc;
    @Autowired private UserRepository users;
    @Autowired private FindingRepository findings;
    @Autowired private AuditLogRepository auditLog;

    private User analyst;
    private User reviewer;

    @BeforeEach
    void setUp() {
        analyst = users.save(new User(ANALYST, "Report Analyst", "x", Role.ANALYST));
        reviewer = users.save(new User("reviewer@posture-report.test", "Report Reviewer", "x", Role.REVIEWER));
        // CVSS 10.0 → effective risk 10.0: guaranteed into the top-risks table over any dev-DB data.
        seed("CM-PRT-0001", "Posture report critical finding", Severity.CRITICAL,
                new BigDecimal("10.0"), FindingStatus.OPEN);
        Finding accepted = seed("CM-PRT-0002", "Posture report accepted risk", Severity.HIGH,
                new BigDecimal("8.1"), FindingStatus.ACCEPTED);
        // Acceptance provenance: the reviewer's transition event backs the "Accepted by" column.
        auditLog.save(new AuditLog(accepted, reviewer, "accept-risk",
                FindingStatus.IN_PROGRESS, FindingStatus.ACCEPTED, "Compensating control in place"));
    }

    private Finding seed(String reference, String title, Severity severity, BigDecimal cvss, FindingStatus status) {
        Finding f = findings.save(new Finding(reference, title, "d", severity, cvss, analyst,
                new Asset("posture-svc", null, null, null)));
        f.setStatus(status);
        return findings.save(f);
    }

    @Test
    @WithMockUser(username = ANALYST)
    void pdfRendersCoverChartsInsightsAndTables() throws Exception {
        MvcResult result = mockMvc.perform(get("/api/reports/posture?format=pdf"))
                .andExpect(status().isOk())
                .andExpect(r -> assertThat(r.getResponse().getContentType()).isEqualTo("application/pdf"))
                .andExpect(r -> assertThat(r.getResponse().getHeader("Content-Disposition"))
                        .contains("attachment").contains("posture-").contains(".pdf"))
                .andReturn();

        try (PDDocument doc = Loader.loadPDF(result.getResponse().getContentAsByteArray())) {
            assertThat(doc.getNumberOfPages()).isGreaterThanOrEqualTo(3);   // cover + content + methodology
            String text = new PDFTextStripper().getText(doc);
            assertThat(text)
                    .contains("Security posture report")
                    .contains("Generated by Report Analyst (Analyst)")      // provenance
                    .contains("Overall risk posture")
                    .contains("Findings by severity")
                    .contains("Risk concentration")
                    .contains("Key insights")
                    .contains("Recommended actions")
                    .contains("Top risks")
                    .contains("CM-PRT-0001")                                 // the guaranteed top risk
                    .contains("Risk acceptances")
                    .contains("CM-PRT-0002")
                    .contains("Report Reviewer")                             // who accepted it
                    .contains("Control coverage by framework")
                    .contains("Coverage gaps")
                    .contains("Methodology & definitions")
                    .contains("Page 1 of");                                  // footer pass ran
        }
    }

    @Test
    @WithMockUser(username = ANALYST)
    void csvCompanionCarriesTheRawBlocks() throws Exception {
        MvcResult result = mockMvc.perform(get("/api/reports/posture?format=csv"))
                .andExpect(status().isOk())
                .andExpect(r -> assertThat(r.getResponse().getContentType()).startsWith("text/csv"))
                .andReturn();
        String csv = new String(result.getResponse().getContentAsByteArray(), StandardCharsets.UTF_8);
        assertThat(csv)
                .startsWith("﻿")                                        // UTF-8 BOM
                .contains("Security posture report")
                .contains("Posture score,")
                .contains("Posture band,")
                .contains("Findings by severity")
                .contains("Critical,")
                .contains("Key insights")
                .contains("CM-PRT-0001")
                .contains("Risk acceptances")
                .contains("Coverage gaps");
    }

    @Test
    @WithMockUser(username = ANALYST)
    void unknownFormatIsRejected() throws Exception {
        mockMvc.perform(get("/api/reports/posture?format=xlsx")).andExpect(status().isBadRequest());
    }

    @Test
    void unauthenticatedIsUnauthorized() throws Exception {
        mockMvc.perform(get("/api/reports/posture")).andExpect(status().isUnauthorized());
    }

    @Test
    void topRisksSortsActiveByRiskDescAndCaps() {
        FindingSummary top = summary("A", "9.8", "open");
        FindingSummary mid = summary("B", "7.5", "in-progress");
        FindingSummary low = summary("C", "2.0", "returned");
        FindingSummary closed = summary("D", "10.0", "remediated");          // inactive: excluded
        List<FindingSummary> ranked = PostureReportService.topRisks(List.of(low, closed, top, mid), 2);
        assertThat(ranked).extracting(FindingSummary::reference).containsExactly("A", "B");
    }

    private static FindingSummary summary(String ref, String risk, String status) {
        Instant now = Instant.parse("2026-07-03T00:00:00Z");
        return new FindingSummary(1L, ref, "t", null, "high", null,
                new BigDecimal(risk), "cvss", status, List.of(), "o", now, now);
    }
}
