package io.muzoo.ssc.controlmap.web;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.matchesRegex;
import static org.hamcrest.Matchers.not;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import io.muzoo.ssc.controlmap.domain.Role;
import io.muzoo.ssc.controlmap.domain.User;
import io.muzoo.ssc.controlmap.repository.UserRepository;
import java.nio.charset.StandardCharsets;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;

/**
 * The ADMIN-only user-management audit export: role gate (403 analyst, 401 anonymous), CSV body
 * (clean table, both parties' emails, fixed-precision timestamps) and PDF rendering (provenance +
 * footer). Audit rows are produced through the real admin API, not inserted directly.
 */
@SpringBootTest
@AutoConfigureMockMvc
@Transactional
class UserAuditReportTest {

    private static final String ADMIN = "admin@uar.test";
    private static final String ANALYST = "analyst@uar.test";

    @Autowired private MockMvc mockMvc;
    @Autowired private UserRepository users;

    private User analyst;

    @BeforeEach
    void setUp() {
        users.save(new User(ADMIN, "Audit Admin", "x", Role.ADMIN));
        analyst = users.save(new User(ANALYST, "Audit Analyst", "x", Role.ANALYST));
    }

    /** Drives a real role change so a genuine "role-changed" audit row exists. */
    private void promoteAnalyst() throws Exception {
        mockMvc.perform(put("/api/users/" + analyst.getId() + "/role").with(csrf())
                        .contentType(MediaType.APPLICATION_JSON).content("{\"role\":\"REVIEWER\"}"))
                .andExpect(status().isOk());
    }

    @Test
    @WithMockUser(username = ADMIN, roles = "ADMIN")
    void csvListsAdminActionsWithBothEmails() throws Exception {
        promoteAnalyst();
        byte[] body = mockMvc.perform(get("/api/reports/user-audit").param("format", "csv"))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith("text/csv"))
                .andExpect(header().string("Content-Disposition", containsString("user-audit-log-")))
                // fixed-precision UTC timestamps, same convention as the finding audit export.
                .andExpect(content().string(matchesRegex("(?s).*\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2} UTC,.*")))
                // the CSV stays a clean header+rows table — provenance is PDF-only.
                .andExpect(content().string(not(containsString("Generated by"))))
                .andReturn().getResponse().getContentAsByteArray();
        // Decode as UTF-8 ourselves: text/csv declares no charset, so getContentAsString would
        // fall back to ISO-8859-1 and mangle the non-ASCII arrow in the role-change detail.
        String csv = new String(body, StandardCharsets.UTF_8);
        assertThat(csv)
                .contains("Timestamp,Actor,Actor email,Action,Target user,Target email,Detail")
                // actor and target are each pinned by name + immutable email; the detail keeps the roles.
                .contains("Audit Admin," + ADMIN + ",role-changed,Audit Analyst," + ANALYST)
                .contains("ANALYST → REVIEWER");
    }

    @Test
    @WithMockUser(username = ADMIN, roles = "ADMIN")
    void pdfCarriesProvenanceAndFooter() throws Exception {
        promoteAnalyst();
        byte[] body = mockMvc.perform(get("/api/reports/user-audit").param("format", "pdf"))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_PDF))
                .andExpect(header().string("Content-Disposition", containsString(".pdf")))
                .andReturn().getResponse().getContentAsByteArray();
        assertThat(new String(body, 0, 5, StandardCharsets.US_ASCII)).startsWith("%PDF-");
        try (PDDocument doc = Loader.loadPDF(body)) {
            String text = new PDFTextStripper().getText(doc).replaceAll("\\s+", " ");
            assertThat(text).contains("User management audit log").contains("Target email");
            assertThat(text).contains("role-changed").contains("ANALYST -> REVIEWER"); // arrow transliterated
            assertThat(text).contains("Generated by Audit Admin (Admin)");
            assertThat(text).contains("AuditYote - User management audit log").contains("Page 1 of");
        }
    }

    @Test
    @WithMockUser(username = ANALYST)
    void nonAdminIs403() throws Exception {
        mockMvc.perform(get("/api/reports/user-audit").param("format", "csv"))
                .andExpect(status().isForbidden());
    }

    @Test
    void unauthenticatedIs401() throws Exception {
        mockMvc.perform(get("/api/reports/user-audit")).andExpect(status().isUnauthorized());
    }
}
